version: '3'
services:
  web:
    container_name: frontend-container
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - flaskapp
    expose:
      - 8000
  flaskapp:
    container_name: flaskapp
    hostname: flaskapp
    build: ./backend
    entrypoint: python run.py
    env_file:
      - ./backend/flaskapp/.env
    ports:
      - '5000:5000'
    depends_on:
      - db

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
  db:
    image: postgres
    hostname: postgres
    volumes:
      - ./instance/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=bpp
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
